// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Abilities struct {
	ID      string `json:"id"`
	Action  string `json:"action"`
	Subject string `json:"subject"`
}

type Address struct {
	ID           string       `json:"id"`
	FloorNo      int          `json:"floor_no"`
	AppartmentNo int          `json:"appartment_no"`
	LandMark     string       `json:"land_mark"`
	Street       string       `json:"street"`
	City         string       `json:"city"`
	State        string       `json:"state"`
	Country      string       `json:"country"`
	Coordinates  *Coordinates `json:"coordinates"`
}

type Admin struct {
	ID        string     `json:"id"`
	UserInfo  *User      `json:"user_info"`
	UserID    string     `json:"user_id"`
	Addresses []*Address `json:"addresses"`
	Manages   []*Seller  `json:"manages"`
}

type Coordinates struct {
	Lat int `json:"lat"`
	Lng int `json:"lng"`
}

type Customer struct {
	ID        string     `json:"id"`
	UserInfo  *User      `json:"user_info"`
	UserID    string     `json:"user_id"`
	Addresses []*Address `json:"addresses"`
}

type Image struct {
	ID   string  `json:"id"`
	Path *string `json:"path"`
	Name *string `json:"name"`
}

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Name struct {
	Ar *string `json:"ar"`
	En *string `json:"en"`
}

type Product struct {
	ProductName   *Name              `json:"product_name"`
	Unit          *string            `json:"unit"`
	MinQty        *int               `json:"min_qty"`
	MaxQty        *int               `json:"max_qty"`
	Status        *int               `json:"status"`
	ProductImages *ProductImages     `json:"product_images"`
	Variant       []*Variant         `json:"variant"`
	Sku           *string            `json:"sku"`
	Alias         *string            `json:"alias"`
	Warranty      *bool              `json:"warranty"`
	Discount      *float64           `json:"discount"`
	Attributes    []*AttributesData  `json:"attributes"`
	Seo           *SeoData           `json:"seo"`
	Brand         *ProductBrand      `json:"brand"`
	Categories    *ProductCategories `json:"categories"`
}

type Role struct {
	ID      string       `json:"id"`
	Name    string       `json:"name"`
	Ability []*Abilities `json:"ability"`
}

type Seller struct {
	ID        string     `json:"id"`
	UserInfo  *User      `json:"user_info"`
	UserID    string     `json:"user_id"`
	Addresses []*Address `json:"addresses"`
	Shops     []*Shops   `json:"shops"`
}

type Shops struct {
	ID      string        `json:"id"`
	Name    *BusinessName `json:"name"`
	Address *Address      `json:"address"`
}

type User struct {
	ID        string     `json:"id"`
	FirstName *FirstName `json:"first_name"`
	LastName  *LastName  `json:"last_name"`
	Email     string     `json:"email"`
	Password  string     `json:"password"`
	Mobile    *int       `json:"mobile"`
	Role      *Role      `json:"role"`
	IsActive  *bool      `json:"isActive"`
}

type AttributesData struct {
	ID    string  `json:"id"`
	Name  *Name   `json:"name"`
	Value *string `json:"value"`
}

type BusinessName struct {
	Ar *string `json:"ar"`
	En *string `json:"en"`
}

type FirstName struct {
	Ar *string `json:"ar"`
	En *string `json:"en"`
}

type LastName struct {
	Ar *string `json:"ar"`
	En *string `json:"en"`
}

type NewAbilities struct {
	ID      string `json:"id"`
	Action  string `json:"action"`
	Subject string `json:"subject"`
}

type NewAddress struct {
	ID           string          `json:"id"`
	FloorNo      int             `json:"floor_no"`
	AppartmentNo int             `json:"appartment_no"`
	LandMark     string          `json:"land_mark"`
	Street       string          `json:"street"`
	City         string          `json:"city"`
	State        string          `json:"state"`
	Country      string          `json:"country"`
	Coordinates  *NewCoordinates `json:"coordinates"`
}

type NewAdmin struct {
	ID        *string     `json:"id"`
	UserInfo  *NewUser    `json:"user_info"`
	UserID    string      `json:"user_id"`
	Addresses *NewAddress `json:"addresses"`
	Manages   *NewSeller  `json:"manages"`
}

type NewBusinessName struct {
	Ar *string `json:"ar"`
	En *string `json:"en"`
}

type NewCoordinates struct {
	Lat int `json:"lat"`
	Lng int `json:"lng"`
}

type NewCustomer struct {
	ID        string      `json:"id"`
	UserInfo  *NewUser    `json:"user_info"`
	UserID    string      `json:"user_id"`
	Addresses *NewAddress `json:"addresses"`
}

type NewFirstName struct {
	Ar *string `json:"ar"`
	En *string `json:"en"`
}

type NewImage struct {
	ID   string  `json:"id"`
	Path *string `json:"path"`
	Name *string `json:"name"`
}

type NewLastName struct {
	Ar *string `json:"ar"`
	En *string `json:"en"`
}

type NewLogin struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewName struct {
	Ar *string `json:"ar"`
	En *string `json:"en"`
}

type NewProduct struct {
	ProductName   *NewName              `json:"product_name"`
	Unit          *string               `json:"unit"`
	MinQty        *int                  `json:"min_qty"`
	MaxQty        *int                  `json:"max_qty"`
	Status        *int                  `json:"status"`
	ProductImages *NewproductImages     `json:"product_images"`
	Variant       []*Newvariant         `json:"variant"`
	Sku           *string               `json:"sku"`
	Alias         *string               `json:"alias"`
	Warranty      *bool                 `json:"warranty"`
	Discount      *float64              `json:"discount"`
	Attributes    []*NewattributesData  `json:"attributes"`
	Seo           *NewseoData           `json:"seo"`
	Brand         *NewproductBrand      `json:"brand"`
	Categories    *NewproductCategories `json:"categories"`
}

type NewRole struct {
	ID      string        `json:"id"`
	Name    string        `json:"name"`
	Ability *NewAbilities `json:"ability"`
}

type NewSeller struct {
	ID        *string     `json:"id"`
	UserInfo  *NewUser    `json:"user_info"`
	UserID    string      `json:"user_id"`
	Addresses *NewAddress `json:"addresses"`
	Shops     *NewShops   `json:"shops"`
}

type NewShops struct {
	ID      string           `json:"id"`
	Name    *NewBusinessName `json:"name"`
	Address *NewAddress      `json:"address"`
}

type NewUser struct {
	ID        string        `json:"id"`
	FirstName *NewFirstName `json:"first_name"`
	LastName  *NewLastName  `json:"last_name"`
	Email     string        `json:"email"`
	Password  string        `json:"password"`
	Mobile    *int          `json:"mobile"`
	Role      *NewRole      `json:"role"`
	IsActive  *bool         `json:"isActive"`
}

type NewattributesData struct {
	ID    string   `json:"id"`
	Name  *NewName `json:"name"`
	Value *string  `json:"value"`
}

type NewproductBrand struct {
	ID    string    `json:"id"`
	Name  *string   `json:"name"`
	Image *NewImage `json:"image"`
}

type NewproductCategories struct {
	ID   string   `json:"id"`
	Name *NewName `json:"name"`
}

type NewproductGallery struct {
	Image []*NewImage `json:"image"`
}

type NewproductImages struct {
	Thumbnail *string            `json:"thumbnail"`
	Gallery   *NewproductGallery `json:"gallery"`
}

type NewseoData struct {
	Title *string   `json:"title"`
	Desc  *string   `json:"desc"`
	Image *NewImage `json:"image"`
}

type Newvariant struct {
	Name  *NewName `json:"name"`
	Value *string  `json:"value"`
}

type ProductBrand struct {
	ID    string  `json:"id"`
	Name  *string `json:"name"`
	Image *Image  `json:"image"`
}

type ProductCategories struct {
	ID   string `json:"id"`
	Name *Name  `json:"name"`
}

type ProductGallery struct {
	Image []*Image `json:"image"`
}

type ProductImages struct {
	Thumbnail *string         `json:"thumbnail"`
	Gallery   *ProductGallery `json:"gallery"`
}

type SeoData struct {
	Title *string `json:"title"`
	Desc  *string `json:"desc"`
	Image *Image  `json:"image"`
}

type UserData struct {
	UserData *User  `json:"userData"`
	Token    string `json:"token"`
}

type Variant struct {
	Name  *Name   `json:"name"`
	Value *string `json:"value"`
}
